### ISSUE TITLE
fix(update): repair main — update_test.go calls ReplaceBinary with stale signature (vet/typecheck broken)

### ISSUE THREAD

**Issue by corylanou** [digitaldrywood/detent#353]
## Problem
Main is broken at `ad03d7b` (test-compile failure) from a **semantic conflict** between independently-green PRs merged in the same train: one PR changed `ReplaceBinary` to take a `context.Context` first parameter, another added/kept tests calling the old signature.

```
internal/update/update_test.go:1069:23: not enough arguments in call to ReplaceBinary
internal/update/update_test.go:1086:3:  not enough arguments in call to ReplaceBinary
	have (Replacement)
	want (context.Context, Replacement)
```

`go build ./...` passes; `go vet ./...` and `golangci-lint` (typecheck) fail. Every new PR's CI will fail until this lands.

## Fix
Update the two `ReplaceBinary` call sites in `internal/update/update_test.go` (~:1069, ~:1086) to pass a context (`t.Context()` or `context.Background()`), matching the new `ReplaceBinary(context.Context, Replacement)` signature.

## Acceptance criteria
- `go vet ./...` and `golangci-lint run ./...` pass on main.
- `make check` green.

**Comment by corylanou** [comment]
## Codex Workpad

### Status
Done

### Plan
- [x] Verify worktree isolation and confirm the issue has no unmerged dependencies.
- [x] Reproduce the stale `ReplaceBinary` test compile failure.
- [x] Update the stale `internal/update/update_test.go` call to pass a context.
- [x] Fix the exposed `errorlint` failure in `internal/web/server_test.go` so the full gate can pass.
- [x] Run focused validation and the full `make check` gate.
- [x] Push PR #354 and verify CI.

### Changes
- `internal/update/update_test.go`: pass `context.Background()` to `ReplaceBinary` in `TestReplaceBinaryPreservesValidDarwinSignature`.
- `internal/web/server_test.go`: replace a direct `net.Error` assertion with `errors.As`, resolving the lint failure surfaced after the typecheck repair.

### Validation Evidence
- Reproduced before fix: `go test ./internal/update` failed with `not enough arguments in call to ReplaceBinary`.
- `go test ./internal/update` passed.
- `go test ./internal/web` passed.
- `go vet ./...` passed.
- `golangci-lint run ./...` passed with `0 issues`.
- `make check` passed after rebasing onto `origin/main` at `f257743`; coverage gate reported `79.0% meets 70.0% threshold`.
- CI on PR #354 head `32cd299280947b5a6253691bb8a1bd8d6f9aa5ab` passed: Lint, Test Coverage, Verify ubuntu/macos/windows, Windows Core, and GoReleaser Snapshot.

### PR
- https://github.com/digitaldrywood/detent/pull/354
- Merged at `2026-06-11T00:46:02Z` as merge commit `1a0cff68ba16fcd9e0b296b8b92ac77cfbb3703a`.
- `Fixes #353` closed the issue automatically.

### Blockers
None.
